const REFETCH_CHATS = "REFETCH_CHATS";
const ALERT = "ALERT";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

export { REFETCH_CHATS, ALERT, NEW_ATTACHMENT, NEW_MESSAGE_ALERT };
